# fly.toml file for music-backend
app = "tfg-music-backend"
primary_region = "gru"

[build]
  dockerfile = "../../Dockerfile"
  target = "music-backend"

[env]
  # ATENÇÃO: Substitua pelos seus tokens reais do Spotify
  SPOTIFY_CLIENT_ID = "6b5cdcb34b384ce795186aae26220918"
  SPOTIFY_CLIENT_SECRET = "bd24ed38cfbd46b0ba1243132a1a7c38"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"